'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3615
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("QuickDALLibrary.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property Critical() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Critical", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Information() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Information", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Question() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Question", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF NOT EXISTS (SELECT o.[NAME] FROM sysobjects o WHERE o.[Name] =&apos;Sec_Menu_Role_Association&apos;)
        '''	BEGIN
        '''	CREATE TABLE Sec_Menu_Role_Association(
        '''		[Co_ID] [smallint] NOT NULL,
        '''		[Menu_ID] [int] NOT NULL,
        '''		[Role_ID] [int] NOT NULL,
        '''		[Stamp_DateTime] [datetime] NOT NULL,
        '''		[Stamp_UserID] [int] NOT NULL,
        '''		[Upload_DateTime] [datetime] NULL,
        '''	 CONSTRAINT PK_Sec_Menu_Role_Association PRIMARY KEY CLUSTERED 
        '''	(
        '''		[Co_ID] ASC,
        '''		[Menu_ID] ASC,
        '''		[Role_ID] ASC
        '''	)
        '''	) ON [PRIMARY]
        '''	END
        '''GO
        '''IF NOT EXIST [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property upgrade_02_00_00_12_to_02_01_00_01() As String
            Get
                Return ResourceManager.GetString("upgrade_02_00_00_12_to_02_01_00_01", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF NOT EXISTS (SELECT C.[NAME] FROM sysobjects o INNER JOIN syscolumns c ON o.id=c.id WHERE o.[Name] =&apos;Accounting_Voucher_Detail&apos; AND c.[Name]=&apos;CustomDate1&apos;) 
        '''ALTER TABLE Accounting_Voucher_Detail ADD CustomDate1 datetime NULL
        '''go
        '''IF NOT EXISTS (SELECT C.[NAME] FROM sysobjects o INNER JOIN syscolumns c ON o.id=c.id WHERE o.[Name] =&apos;Accounting_Voucher_Detail&apos; AND c.[Name]=&apos;CustomDate2&apos;) 
        '''ALTER TABLE Accounting_Voucher_Detail ADD CustomDate2 datetime NULL
        '''go
        '''IF NOT EXISTS (SELECT C.[NAME] FROM sysobjects [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property upgrade_02_01_00_06_to_02_01_00_07() As String
            Get
                Return ResourceManager.GetString("upgrade_02_01_00_06_to_02_01_00_07", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to --Primary needs to be changed so change the duplicate inventory_id to new ones
        '''--Updates duplicate items in detail table which was not updated by above query.
        '''DECLARE @Co_ID AS INT, @Inventory_ID AS INT, @DocumentType_ID AS INT, @Inventory_Detail_ID AS INT, @New_ID AS INT, @New_Detail_ID AS INT, @Count AS INT
        '''
        '''WHILE EXISTS (SELECT Co_ID, Inventory_ID FROM Inventory_Detail GROUP BY Co_ID, Inventory_ID, InventoryDetail_ID HAVING COUNT(*) &gt; 1)
        '''	BEGIN
        '''		SELECT @Co_ID=Co_ID, @Inventory_ID=Inventory_ID, @Do [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property upgrade_02_01_00_09_to_02_02_00_00() As String
            Get
                Return ResourceManager.GetString("upgrade_02_01_00_09_to_02_02_00_00", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF EXISTS (SELECT Status_ID FROM Sec_Menu_Role_Association WHERE Status_ID IS NULL)
        '''	BEGIN
        '''		UPDATE Sec_Menu_Role_Association SET Status_ID = 10 WHERE Status_ID IS NULL
        '''		ALTER TABLE Sec_Menu_Role_Association ALTER COLUMN Status_ID INT NOT NULL
        '''	END
        '''go
        '''IF NOT EXISTS (SELECT C.[NAME] FROM sysobjects o INNER JOIN syscolumns c ON o.id=c.id WHERE o.[Name] =&apos;Common_Status&apos; AND c.[Name]=&apos;Upload_DateTime&apos;) 
        '''	ALTER TABLE Common_Status ADD Upload_DateTime DATETIME NULL
        '''go
        '''IF NOT EXISTS (SELECT C.[NAME] FROM [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property upgrade_02_02_00_00_to_02_02_01_00() As String
            Get
                Return ResourceManager.GetString("upgrade_02_02_00_00_to_02_02_01_00", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF NOT EXISTS (SELECT o.[NAME] FROM sysobjects o WHERE o.[Name] =&apos;Inv_Warehouse&apos;)
        '''	CREATE TABLE Inv_Warehouse 
        '''		(Co_ID SMALLINT NOT NULL,
        '''		Warehouse_ID INT NOT NULL,
        '''		Warehouse_Name VARCHAR(100) NOT NULL,
        '''		Stamp_UserID INT NOT NULL,
        '''		Stamp_DateTime DATETIME NOT NULL,
        '''		Upload_DateTime DATETIME NULL,
        '''		
        '''		CONSTRAINT PK_Inv_Warehouse PRIMARY KEY CLUSTERED
        '''		(
        '''		Co_ID ASC, Warehouse_ID ASC
        '''		))
        '''GO
        '''IF NOT EXISTS (SELECT C.[NAME] FROM sysobjects o INNER JOIN syscolumns c ON o.id=c.id WHERE o.[ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property upgrade_02_02_01_02_to_02_03_00_00() As String
            Get
                Return ResourceManager.GetString("upgrade_02_02_01_02_to_02_03_00_00", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF NOT EXISTS (SELECT * FROM Common_Status_Type WHERE Status_Type_ID = 0)
        '''	INSERT INTO [Common_Status_Type]
        '''		([Status_Type_ID], [Status_Type_Desc], [Stamp_DateTime], [Stamp_UserID], [Upload_DateTime])
        '''		 VALUES (0, &apos;Apply to All&apos;, &apos;2009/04/22&apos;, 0, NULL)
        '''GO
        '''IF NOT EXISTS (SELECT * FROM Common_Status_Type WHERE Status_Type_ID = 1)
        '''	INSERT INTO [Common_Status_Type]
        '''		([Status_Type_ID], [Status_Type_Desc], [Stamp_DateTime], [Stamp_UserID], [Upload_DateTime])
        '''		 VALUES (1, &apos;Transfer Data&apos;, &apos;2009/04/22&apos;, [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property upgrade_02_03_00_00_to_02_03_00_01() As String
            Get
                Return ResourceManager.GetString("upgrade_02_03_00_00_to_02_03_00_01", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF NOT EXISTS (SELECT C.[NAME] FROM sysobjects o INNER JOIN syscolumns c ON o.id=c.id WHERE o.[Name] =&apos;Sec_User&apos; AND c.[Name]=&apos;Is_Admin&apos;)
        '''	ALTER TABLE Sec_User ADD Is_Admin BIT NULL
        '''go
        '''IF NOT EXISTS (SELECT C.[NAME] FROM sysobjects o INNER JOIN syscolumns c ON o.id=c.id WHERE o.[Name] =&apos;Accounting_Voucher_Detail&apos; AND c.[Name]=&apos;Party_ID&apos;)
        '''	ALTER TABLE Accounting_Voucher_Detail ADD Party_ID INT NULL.
        '''</summary>
        Friend ReadOnly Property upgrade_02_03_00_01_to_02_03_00_02() As String
            Get
                Return ResourceManager.GetString("upgrade_02_03_00_01_to_02_03_00_02", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF NOT EXISTS (SELECT C.[NAME] FROM sysobjects o INNER JOIN syscolumns c ON o.id=c.id WHERE o.[Name] =&apos;Accounting_Voucher_Detail&apos; AND c.[Name]=&apos;Party_ID&apos;)
        '''	ALTER TABLE Accounting_Voucher_Detail ADD Party_ID INT NULL
        '''go
        '''UPDATE Sec_User Set Is_Admin = 1, Stamp_DateTime = GetDate().
        '''</summary>
        Friend ReadOnly Property upgrade_02_03_00_02_to_02_03_00_03() As String
            Get
                Return ResourceManager.GetString("upgrade_02_03_00_02_to_02_03_00_03", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF NOT EXISTS (SELECT Menu_Id FROM Base_Menu WHERE Menu_Id =108) 
        '''	INSERT INTO [Base_Menu] 
        '''		([Menu_Id], [Menu_Desc], [Form_Id], 
        '''		[Display_Order], [Parent_Menu_Id], [Stamp_UserId], 
        '''		[Stamp_DateTime], [Upload_DateTime]) 
        '''		VALUES (108, &apos;Sales Re&amp;turn&apos;, &apos;01-008&apos;, 8, 100, 0, &apos;2009/05/16&apos;, NULL)
        '''GO
        '''UPDATE Inv_ItemSummary SET Warehouse_ID = 0 WHERE Warehouse_ID IS NULL
        '''GO
        '''IF NOT EXISTS (SELECT * FROM Inv_ItemSummary WHERE Warehouse_ID IS NULL)
        '''	ALTER TABLE Inv_ItemSummary
        '''		ALTER COLUMN Warehouse [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property upgrade_02_03_00_08_to_02_03_00_09() As String
            Get
                Return ResourceManager.GetString("upgrade_02_03_00_08_to_02_03_00_09", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF NOT EXISTS (SELECT C.[NAME] FROM sysobjects o INNER JOIN syscolumns c ON o.id=c.id WHERE o.[Name] =&apos;Accounting_VoucherType&apos; AND c.[Name]=&apos;Inactive_From&apos;)
        '''	ALTER TABLE Accounting_VoucherType ADD Inactive_From DATETIME NULL
        '''GO
        '''IF NOT EXISTS (SELECT C.[NAME] FROM sysobjects o INNER JOIN syscolumns c ON o.id=c.id WHERE o.[Name] =&apos;Accounting_VoucherType&apos; AND c.[Name]=&apos;Inactive_To&apos;)
        '''	ALTER TABLE Accounting_VoucherType ADD Inactive_To DATETIME NULL
        '''go
        '''IF NOT EXISTS (SELECT C.[NAME] FROM sysobjects o INNER [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property upgrade_02_03_00_12_to_02_03_00_13() As String
            Get
                Return ResourceManager.GetString("upgrade_02_03_00_12_to_02_03_00_13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to -- =============================================
        '''-- Author:		Noman Latif
        '''-- Create date: 28 Sep 2008
        '''-- Description:	This stored procedure is used for
        '''--              to calculate the stock.
        '''-- =============================================
        '''-- ------------ Modification History -----------
        '''-- Author	Date		Details
        '''-- ------   ----        -------
        '''-- Faisal	20-Jun-2009	Add field of remarks to show in daily stock report.
        '''-- ---------------------------------------------
        '''ALTER PROCEDURE [spDailyStock]
        '''	 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property upgrade_02_03_00_13_to_02_03_00_14() As String
            Get
                Return ResourceManager.GetString("upgrade_02_03_00_13_to_02_03_00_14", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF NOT EXISTS (SELECT o.[NAME] FROM sysobjects o WHERE o.[Name] =&apos;Inv_ItemSize&apos;)
        '''	CREATE TABLE Inv_ItemSize
        '''		(Co_ID SMALLINT NOT NULL,
        '''		ItemSize_ID SMALLINT NOT NULL,
        '''		Stamp_UserID INT NOT NULL,
        '''		Stamp_DateTime DATETIME NOT NULL,
        '''		Upload_DateTime DATETIME NULL,
        '''
        '''		CONSTRAINT PK_Inv_ItemSize PRIMARY KEY CLUSTERED
        '''		(Co_ID ASC, ItemSize_ID ASC)
        '''		)
        '''GO
        '''IF NOT EXISTS (SELECT o.[NAME] FROM sysobjects o WHERE o.[Name] =&apos;Inv_ItemSize_History&apos;)
        '''	CREATE TABLE Inv_ItemSize_History
        '''		(History_ID INT [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property upgrade_02_03_00_14_to_02_03_00_15() As String
            Get
                Return ResourceManager.GetString("upgrade_02_03_00_14_to_02_03_00_15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to -- =============================================
        '''-- Author:		Noman Latif
        '''-- Create date: 28 Sep 2008
        '''-- Description:	This stored procedure is used for
        '''--              to calculate the stock.
        '''-- =============================================
        '''-- ------------ Modification History -----------
        '''-- Author	Date		Details
        '''-- ------   ----        -------
        '''-- Faisal	20-Jun-2009	Add field of remarks to show in daily stock report.
        '''-- Faisal	06-Aug-2009	Inventory_ID column is added so that it can be grouped in rep [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property upgrade_02_03_00_15_to_02_03_00_16() As String
            Get
                Return ResourceManager.GetString("upgrade_02_03_00_15_to_02_03_00_16", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF NOT EXISTS (SELECT Menu_Id FROM Base_Menu WHERE Menu_Id =602)
        '''	INSERT INTO [Base_Menu]
        '''		([Menu_Id], [Menu_Desc], [Form_Id],
        '''		[Display_Order], [Parent_Menu_Id], [Stamp_UserId],
        '''		[Stamp_DateTime], [Upload_DateTime])
        '''		VALUES (602, &apos;&amp;Users&apos;, &apos;06-002&apos;, 2, 600, 0, &apos;2009-08-08&apos;, NULL)
        '''GO
        '''IF NOT EXISTS (SELECT Menu_Id FROM Base_Menu WHERE Menu_Id =603)
        '''	INSERT INTO [Base_Menu]
        '''		([Menu_Id], [Menu_Desc], [Form_Id],
        '''		[Display_Order], [Parent_Menu_Id], [Stamp_UserId],
        '''		[Stamp_DateTime], [Upload_Dat [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property upgrade_02_03_00_16_to_02_03_00_17() As String
            Get
                Return ResourceManager.GetString("upgrade_02_03_00_16_to_02_03_00_17", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE FROM Base_Alert WHERE Alert_DateTime &lt; &apos;2008-08-23&apos;
        '''go
        '''UPDATE Base_Alert SET Alert_Destination = &apos;quickerp@quicktijarat.com&apos;, Stamp_DateTime = &apos;2009-09-14&apos; 
        '''WHERE Alert_Type = 0 AND Status_ID = 8.
        '''</summary>
        Friend ReadOnly Property upgrade_02_03_00_19_to_02_03_00_20() As String
            Get
                Return ResourceManager.GetString("upgrade_02_03_00_19_to_02_03_00_20", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF EXISTS (SELECT o.[NAME] FROM sysobjects o WHERE o.[Name] =&apos;Invs_Inventory_Detail&apos;)
        '''	DROP TABLE Invs_Inventory_Detail
        '''go
        '''IF EXISTS (SELECT o.[NAME] FROM sysobjects o WHERE o.[Name] =&apos;Invs_Inventory&apos;)
        '''	DROP TABLE Invs_Inventory
        '''go
        '''IF EXISTS (SELECT o.[NAME] FROM sysobjects o WHERE o.[Name] =&apos;Invs_Inventory_Detail_History&apos;)
        '''	DROP TABLE Invs_Inventory_Detail_History
        '''go
        '''IF EXISTS (SELECT o.[NAME] FROM sysobjects o WHERE o.[Name] =&apos;Invs_Inventory_History&apos;)
        '''	DROP TABLE Invs_Inventory_History
        '''go
        '''IF E [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property upgrade_02_03_00_20_to_02_03_01_00() As String
            Get
                Return ResourceManager.GetString("upgrade_02_03_00_20_to_02_03_01_00", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF NOT EXISTS (SELECT [Setting_Id] FROM [Base_Setting] WHERE [Setting_Id] =&apos;DBColumnCaptionQty_Total&apos;)
        '''	INSERT INTO [Base_Setting]
        '''       ([Co_Id], [User_Id], [Setting_Id]
        '''       , [Setting_Desc]
        '''       ,[Setting_Value], [Stamp_User_Id], [Stamp_DateTime], [Setting_Value_DataType]
        '''       ,[Setting_Value_MinimumValue], [Setting_Value_MaximumValue], [Upload_DateTime])
        '''  VALUES
        '''       (0,0,&apos;DBColumnCaptionQty_Total&apos;
        '''       ,&apos;Qty_Total Caption&apos;
        '''       ,&apos;Total&apos;,0,&apos;2009/11/09&apos;,&apos;String&apos;
        '''       ,NULL,NULL, [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property upgrade_02_03_01_01_to_02_03_01_02() As String
            Get
                Return ResourceManager.GetString("upgrade_02_03_01_01_to_02_03_01_02", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF NOT EXISTS (SELECT C.[NAME] FROM sysobjects o INNER JOIN syscolumns c ON o.id=c.id WHERE o.[Name] =&apos;Accounting_Voucher_Detail&apos; AND c.[Name]=&apos;Status_ID&apos;)
        '''	ALTER TABLE Accounting_Voucher_Detail ADD Status_ID INT NULL
        '''go
        '''IF NOT EXISTS (SELECT o.[NAME] FROM sysobjects o WHERE o.[Name] =&apos;Accounting_FinancialAccountType&apos;)
        '''	CREATE TABLE [Accounting_FinancialAccountType](
        '''		[FinancialAccountType_ID] SMALLINT NOT NULL,
        '''		[FinancialAccountType_Desc] VARCHAR(50) NOT NULL,
        '''		[Stamp_UserID] INT NULL,
        '''		[Stamp [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property upgrade_02_03_01_04_to_02_03_01_05() As String
            Get
                Return ResourceManager.GetString("upgrade_02_03_01_04_to_02_03_01_05", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF EXISTS (SELECT C.[NAME] FROM sysobjects o INNER JOIN syscolumns c ON o.id=c.id WHERE o.[Name] =&apos;Inventory&apos; AND c.[Name]=&apos;Status_ID&apos;)
        '''	exec sp_rename &apos;Inventory.Status_ID&apos;, &apos;RecordStatus_ID&apos;
        '''GO
        '''IF EXISTS (SELECT o.[NAME] FROM sysobjects o WHERE o.[Name] =&apos;Common_Status&apos;)
        '''	exec sp_rename &apos;Common_Status&apos;, &apos;Common_RecordStatus&apos;
        '''GO
        '''IF EXISTS (SELECT C.[NAME] FROM sysobjects o INNER JOIN syscolumns c ON o.id=c.id WHERE o.[Name] =&apos;Common_RecordStatus&apos; AND c.[Name]=&apos;Status_ID&apos;)
        '''	exec sp_rename &apos;Common_Rec [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property upgrade_02_03_01_05_to_02_03_01_06() As String
            Get
                Return ResourceManager.GetString("upgrade_02_03_01_05_to_02_03_01_06", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF NOT EXISTS (SELECT C.[NAME] FROM sysobjects o INNER JOIN syscolumns c ON o.id=c.id WHERE o.[Name] =&apos;Accounting_COA&apos; AND c.[Name]=&apos;Parent_COA_ID&apos;)
        '''	ALTER TABLE Accounting_COA ADD Parent_COA_ID INT NULL
        '''GO
        '''IF NOT EXISTS (SELECT C.[NAME] FROM sysobjects o INNER JOIN syscolumns c ON o.id=c.id WHERE o.[Name] =&apos;Accounting_COA&apos; AND c.[Name]=&apos;Level_No&apos;)
        '''	ALTER TABLE Accounting_COA ADD Level_No TINYINT NULL
        '''.
        '''</summary>
        Friend ReadOnly Property upgrade_02_03_01_06_to_02_03_01_07() As String
            Get
                Return ResourceManager.GetString("upgrade_02_03_01_06_to_02_03_01_07", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE Base_Setting SET Setting_Value = &apos;P-Y/9999&apos; WHERE Setting_Id = &apos;DocumentNoFormat.SalesInvoice&apos;
        '''.
        '''</summary>
        Friend ReadOnly Property upgrade_02_03_01_07_to_02_03_01_08() As String
            Get
                Return ResourceManager.GetString("upgrade_02_03_01_07_to_02_03_01_08", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ALTER TABLE Inventory_Detail DISABLE TRIGGER ALL
        '''GO
        '''UPDATE Inventory_Detail SET Warehouse_ID = 0 WHERE Warehouse_ID IS NULL
        '''GO
        '''ALTER TABLE Inventory_Detail ENABLE TRIGGER ALL
        '''GO
        '''ALTER TABLE Inventory_Detail
        '''	ALTER COLUMN Warehouse_ID INT NOT NULL
        '''.
        '''</summary>
        Friend ReadOnly Property upgrade_02_03_01_08_to_02_03_01_09() As String
            Get
                Return ResourceManager.GetString("upgrade_02_03_01_08_to_02_03_01_09", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ALTER TABLE Base_Setting
        '''	ALTER COLUMN Setting_Id VARCHAR(100) NOT NULL
        '''GO
        '''IF NOT EXISTS (SELECT [Co_Id] FROM [Base_Setting] WHERE [Co_Id]=0 AND [User_Id]=0 AND [Setting_Id]=&apos;ModificationAllowedPartyCategoryComboBox.SalesInvoiceForm&apos;)
        '''	INSERT INTO [Base_Setting]
        '''			   ([Co_Id]
        '''			   ,[User_Id]
        '''			   ,[Setting_Id]
        '''			   ,[Setting_Desc]
        '''			   ,[Setting_Value]
        '''			   ,[Stamp_User_Id]
        '''			   ,[Stamp_DateTime]
        '''			   ,[Setting_Value_DataType]
        '''			   ,[Setting_Value_MinimumValue]
        '''			   ,[Setting_Value_M [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property upgrade_02_03_01_09_to_02_03_01_10() As String
            Get
                Return ResourceManager.GetString("upgrade_02_03_01_09_to_02_03_01_10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ALTER VIEW [vwStockInquiry]
        '''AS
        '''
        '''SELECT	Co_ID, Co_Code, Item_ID, Item_Code, Item_Category, Item_Desc, SUM(Inventory_Qty_Size01) AS Inventory_Qty_Size01
        '''		, SUM(Inventory_Qty_Size02) AS Inventory_Qty_Size02, SUM(Inventory_Qty_Size03) AS Inventory_Qty_Size03
        '''		, SUM(Inventory_Qty_Size04) AS Inventory_Qty_Size04, SUM(Inventory_Qty_Size05) AS Inventory_Qty_Size05
        '''		, SUM(Inventory_Qty_Size06) AS Inventory_Qty_Size06, SUM(Inventory_Qty_Size07) AS Inventory_Qty_Size07
        '''		, SUM(Inventory_Qty_Size08) AS Invent [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property upgrade_02_03_01_10_to_02_03_01_11() As String
            Get
                Return ResourceManager.GetString("upgrade_02_03_01_10_to_02_03_01_11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF NOT EXISTS (SELECT o.[NAME] FROM sysobjects o WHERE o.[Name] =&apos;Base_SearchOption&apos;)
        '''	CREATE TABLE [Base_SearchOption](
        '''		[SearchOption_ID] INT NOT NULL,
        '''		[SearchOption_Query] VARCHAR(8000) NOT NULL,
        '''		[RecordStatus_ID] INT NOT NULL,
        '''		[Stamp_UserID] INT NOT NULL,
        '''		[Stamp_DateTime] DATETIME NOT NULL,
        '''		[Upload_DateTime] DATETIME NULL,
        '''
        '''	 CONSTRAINT [PK_Base_SearchOption] PRIMARY KEY CLUSTERED 
        '''		(SearchOption_ID ASC)
        '''	)
        '''go
        '''IF NOT EXISTS (SELECT o.[NAME] FROM sysobjects o WHERE o.[Name] =&apos;Bas [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property upgrade_02_03_01_11_to_02_03_01_12() As String
            Get
                Return ResourceManager.GetString("upgrade_02_03_01_11_to_02_03_01_12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF NOT EXISTS (SELECT o.[NAME] FROM sysobjects o WHERE o.[Name] =&apos;Base_SettingForm&apos;)
        '''	CREATE TABLE [Base_SettingForm](
        '''		[Form_ID] SMALLINT NOT NULL,
        '''		[Form_Code] VARCHAR(6) NOT NULL,
        '''		[Form_Name] VARCHAR(100) NOT NULL,
        '''		[RecordStatus_ID] INT NOT NULL,
        '''		[Stamp_UserID] INT NOT NULL,
        '''		[Stamp_DateTime] DATETIME NOT NULL,
        '''		[Upload_DateTime] DATETIME NULL,
        '''
        '''	 CONSTRAINT [PK_Base_SettingForm] PRIMARY KEY CLUSTERED 
        '''		(Form_ID ASC)
        '''	)
        '''go
        '''IF NOT EXISTS (SELECT o.[NAME] FROM sysobjects o WHERE o. [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property upgrade_02_03_01_12_to_02_03_01_13() As String
            Get
                Return ResourceManager.GetString("upgrade_02_03_01_12_to_02_03_01_13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF NOT EXISTS (SELECT C.[NAME] FROM sysobjects o INNER JOIN syscolumns c ON o.id=c.id WHERE o.[Name] =&apos;Base_SearchOption_Detail&apos; AND c.[Name]=&apos;IsHidden&apos;)
        '''	ALTER TABLE Base_SearchOption_Detail ADD IsHidden BIT NULL
        '''go
        '''IF EXISTS (SELECT [SearchOption_ID] FROM [Base_SearchOption_Detail] WHERE [IsHidden] IS NULL)
        '''	BEGIN
        '''		UPDATE Base_SearchOption_Detail SET IsHidden = 0 WHERE IsHidden IS NULL
        '''		ALTER TABLE Base_SearchOption_Detail ALTER COLUMN IsHidden BIT NULL
        '''	END
        '''go
        '''IF NOT EXISTS (SELECT C.[NAME] FR [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property upgrade_02_03_01_14_to_02_03_01_15() As String
            Get
                Return ResourceManager.GetString("upgrade_02_03_01_14_to_02_03_01_15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to -- =============================================
        '''-- Author:		Faisal Saleem
        '''-- Create date: 01-Mar-2009
        '''-- Description:	This stored procedure returns the records from inventory and
        '''--				inventorydetail table to be used in report. It does not perform
        '''--				any calculations.
        '''-- =============================================
        '''-- ------------ Modification History -----------
        '''-- Author	Date		Details
        '''-- ------   ----        -------
        '''-- Faisal	01-Mar-2009	Added Comment header and because primary key is chan [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property upgrade_02_03_02_20_to_02_03_02_21() As String
            Get
                Return ResourceManager.GetString("upgrade_02_03_02_20_to_02_03_02_21", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to if exists (select * from dbo.sysobjects where [name] = &apos;fn_Split&apos;)
        '''	drop function [fn_Split]
        '''go
        '''-- =============================================
        '''-- Author:		Faisal Saleem
        '''-- Create date: 
        '''-- Description:	This function returns the table for the comma seperated
        '''--				values provided as parameter.
        '''-- =============================================
        '''-- ------------ Modification History -----------
        '''-- Author	Date		Details
        '''-- ------   ----        -------
        '''create  FUNCTION fn_Split(@text varchar(8000), @de [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property upgrade_02_03_02_22_to_02_03_02_23() As String
            Get
                Return ResourceManager.GetString("upgrade_02_03_02_22_to_02_03_02_23", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF NOT EXISTS (SELECT C.[NAME] FROM sysobjects o INNER JOIN syscolumns c ON o.id=c.id WHERE o.[Name] =&apos;Accounting_Voucher&apos; AND c.[Name]=&apos;DocumentStatus_ID&apos;)
        '''	ALTER TABLE Accounting_Voucher ADD DocumentStatus_ID INT NULL
        '''	
        '''go
        '''IF EXISTS (SELECT O.[NAME] FROM sysobjects o WHERE o.[Name] =&apos;spGetMenuWithAllowedStatusByCoIDRoleID&apos;)
        '''	DROP PROCEDURE spGetMenuWithAllowedStatusByCoIDRoleID
        '''go
        '''-- ======================================================================
        '''-- Author:		Faisal Saleem
        '''-- Create date: 1 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property upgrade_02_03_02_23_to_02_03_02_24() As String
            Get
                Return ResourceManager.GetString("upgrade_02_03_02_23_to_02_03_02_24", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF NOT EXISTS (SELECT O.[NAME] FROM sysobjects o WHERE o.[Name] =&apos;Dwh_TimeDimension&apos;)
        '''	CREATE TABLE Dwh_TimeDimension
        '''		(
        '''		TimeDimensionID INT NULL,
        '''		YearNumber SMALLINT NULL,
        '''		MonthNumber SMALLINT NULL,
        '''		DayOfMonth SMALLINT NULL,
        '''		DayOfWeek SMALLINT NULL,
        '''		WeekOfYear SMALLINT NULL,
        '''		QuarterNumber SMALLINT NULL,
        '''		IsWeekend BIT NULL,
        '''		IsHoliday BIT NULL,
        '''		IsSeason BIT NULL
        '''		)
        '''go
        '''IF NOT EXISTS (SELECT O.[NAME] FROM sysobjects o WHERE o.[Name] =&apos;Dwh_COADimension&apos;)
        '''	CREATE TABLE Dwh_C [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property upgrade_02_03_02_24_to_02_03_02_25() As String
            Get
                Return ResourceManager.GetString("upgrade_02_03_02_24_to_02_03_02_25", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF NOT EXISTS (SELECT C.[NAME] FROM sysobjects o INNER JOIN syscolumns c ON o.id=c.id WHERE o.[Name] =&apos;Accounting_COA&apos; AND c.[Name]=&apos;Opening_DebitAmount&apos;)
        '''	ALTER TABLE Accounting_COA ADD Opening_DebitAmount DECIMAL NULL
        '''go
        '''IF NOT EXISTS (SELECT C.[NAME] FROM sysobjects o INNER JOIN syscolumns c ON o.id=c.id WHERE o.[Name] =&apos;Accounting_COA&apos; AND c.[Name]=&apos;Opening_CreditAmount&apos;)	
        '''	ALTER TABLE Accounting_COA ADD Opening_CreditAmount DECIMAL NULL.
        '''</summary>
        Friend ReadOnly Property upgrade_02_03_02_25_to_02_03_02_26() As String
            Get
                Return ResourceManager.GetString("upgrade_02_03_02_25_to_02_03_02_26", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to -- =============================================
        '''-- Author:		Faisal
        '''-- Create date: 23-Nov-2008
        '''-- Description:	This trigger updates the ItemSummary table for stock, total purchased, total sold etc.
        '''-- =============================================
        '''-- ------------ Modification History -----------
        '''-- Author	Date		Details
        '''-- ------   ----        -------
        '''-- Faisal	24-Jan-2009	Table name is changed from Inv_Stock to Inv_ItemSummary so the trigger
        '''--						is changed accordingly. Summary_Type field will n [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property upgrade_02_03_02_27_to_02_03_02_28() As String
            Get
                Return ResourceManager.GetString("upgrade_02_03_02_27_to_02_03_02_28", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF EXISTS (SELECT O.[NAME] FROM sysobjects o WHERE o.[Name] =&apos;spGetMinimumStockLevelByItemCodeCompanies&apos;)
        '''	DROP PROC spGetMinimumStockLevelByItemCodeCompanies
        '''go
        '''-- ======================================================================
        '''-- Author:		Faisal Saleem
        '''-- Create date: 29-Aug-10
        '''-- Description:	This procedure returns the minimum stoc level information.
        '''-- ======================================================================
        '''-- ------------ Modification History ------------------------------ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property upgrade_02_03_02_28_to_02_03_02_29() As String
            Get
                Return ResourceManager.GetString("upgrade_02_03_02_28_to_02_03_02_29", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF EXISTS (SELECT O.[NAME] FROM sysobjects o WHERE o.[Name] =&apos;vwStockInquiry&apos;)
        '''	DROP VIEW vwStockInquiry
        '''go
        '''CREATE VIEW vwStockInquiry
        '''AS
        '''SELECT     Co_ID, Co_Code, Warehouse_ID, ISNULL(Warehouse_Name, &apos;Default&apos;) AS Warehouse_Name, Item_ID, Item_Code, dbo.fnGetItemCategoryDesc(Co_ID, Item_Code) AS Item_Category, Item_Desc, SUM(Inventory_Qty_Size01) AS Inventory_Qty_Size01
        '''	, SUM(Inventory_Qty_Size02) AS Inventory_Qty_Size02, SUM(Inventory_Qty_Size03) AS Inventory_Qty_Size03
        '''	, SUM(Inventory_Qty_Size0 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property upgrade_02_03_02_30_to_02_03_02_31() As String
            Get
                Return ResourceManager.GetString("upgrade_02_03_02_30_to_02_03_02_31", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF NOT EXISTS (SELECT C.[NAME] FROM sysobjects o INNER JOIN syscolumns c ON o.id=c.id WHERE o.[Name] =&apos;Accounting_CashFlowAccount&apos; AND c.[Name]=&apos;Co_ID&apos;)
        '''	BEGIN
        '''	TRUNCATE TABLE Accounting_CashFlowAccount
        '''	ALTER TABLE Accounting_CashFlowAccount ADD Co_ID SMALLINT NOT NULL
        '''	ALTER TABLE Accounting_CashFlowAccount
        '''		DROP CONSTRAINT PK_Accounting_CashFlowAccount
        '''	ALTER TABLE Accounting_CashFlowAccount ADD CONSTRAINT
        '''		PK_Accounting_CashFlowAccount PRIMARY KEY CLUSTERED 
        '''		(
        '''		CO_ID,
        '''		CashFlowAccount_ID [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property upgrade_02_03_02_32_to_02_03_02_33() As String
            Get
                Return ResourceManager.GetString("upgrade_02_03_02_32_to_02_03_02_33", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF NOT EXISTS (SELECT * FROM [Base_SettingForm] WHERE [Form_Code] = &apos;01-001&apos;)
        '''	INSERT INTO [Base_SettingForm]
        '''			   ([Form_ID]
        '''			   ,[Form_Code]
        '''			   ,[Form_Name]
        '''			   ,[RecordStatus_ID]
        '''			   ,[Stamp_UserID]
        '''			   ,[Stamp_DateTime]
        '''			   ,[Upload_DateTime])
        '''		 VALUES
        '''			   (1
        '''			   ,&apos;01-001&apos;
        '''			   ,&apos;ItemForm&apos;
        '''			   ,1
        '''			   ,0
        '''			   ,&apos;2010-10-16&apos;
        '''			   ,NULL)
        '''go
        '''IF NOT EXISTS (SELECT * FROM [Base_SettingForm] WHERE [Form_Code] = &apos;01-002&apos;)
        '''	INSERT INTO [Base_SettingForm]
        '''			   ([Form_ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property upgrade_02_03_02_33_to_02_03_02_34() As String
            Get
                Return ResourceManager.GetString("upgrade_02_03_02_33_to_02_03_02_34", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to -- ======================================================================
        '''-- Author:		Faisal Saleem
        '''-- Create date: 29-Aug-10
        '''-- Description:	This procedure returns the minimum stoc level information.
        '''-- ======================================================================
        '''-- ------------ Modification History ------------------------------------
        '''-- Author	Date		Details
        '''-- -------- ---------	-------
        '''-- Faisal	05-Sep-10	Added two columns Warehouse_ID and Warehouse_Name
        '''-- Faisal	20-Oct-10	Added wher [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property upgrade_02_03_02_34_to_02_03_02_35() As String
            Get
                Return ResourceManager.GetString("upgrade_02_03_02_34_to_02_03_02_35", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF NOT EXISTS (SELECT o.[NAME] FROM sysobjects o WHERE o.[Name] =&apos;Production_Process&apos;)
        '''	CREATE TABLE [Production_Process](
        '''		[Co_ID] [smallint] NOT NULL,
        '''		[Process_ID] [smallint] NOT NULL,
        '''		[Process_Code] [varchar](50) NOT NULL,
        '''		[Process_Desc] [varchar](250) NOT NULL,
        '''		[Stamp_UserID] [int] NOT NULL,
        '''		[Stamp_DateTime] [datetime] NOT NULL,
        '''		[Upload_DateTime] [datetime] NULL,
        '''		[RecordStatus_ID] [int] NOT NULL,
        '''	 CONSTRAINT [PK_Production_Process] PRIMARY KEY CLUSTERED
        '''	(
        '''		[Co_ID] ASC,
        '''		[ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property upgrade_02_03_02_35_to_02_03_02_36() As String
            Get
                Return ResourceManager.GetString("upgrade_02_03_02_35_to_02_03_02_36", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF EXISTS (SELECT o.[NAME] FROM sysobjects o WHERE o.[Name] =&apos;SpStockInSummary&apos;)
        '''	DROP PROCEDURE SpStockInSummary
        '''GO
        '''-- ======================================================================
        '''-- Author:		Muhammad Zakee
        '''-- Create date: 29-Sep-10
        '''-- Description:	This procedure returns the Stock In Summary.
        '''-- ======================================================================
        '''-- ------------ Modification History ------------------------------------
        '''-- Author	Date		Details
        '''-- ------   ----        - [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property upgrade_02_03_02_36_to_02_03_02_37() As String
            Get
                Return ResourceManager.GetString("upgrade_02_03_02_36_to_02_03_02_37", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF EXISTS (SELECT o.[NAME] FROM sysobjects o WHERE o.[Name] =&apos;spAddCreateContact&apos;)
        '''	DROP PROCEDURE spAddCreateContact
        '''GO
        '''-- ======================================================================
        '''-- Author:		Faisal Saleem
        '''-- Create date: 28-Dec-10
        '''-- Description:	This procedure will create/add records in all related
        '''--				tables in order to add contact.
        '''-- ======================================================================
        '''-- ------------ Modification History ------------------------------------        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property upgrade_02_03_02_37_to_02_03_02_38() As String
            Get
                Return ResourceManager.GetString("upgrade_02_03_02_37_to_02_03_02_38", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF EXISTS (SELECT o.[NAME] FROM sysobjects o WHERE o.[Name] =&apos;SpGetSalesStockByItemCodeCompany&apos;)
        '''	DROP PROCEDURE SpGetSalesStockByItemCodeCompany
        '''GO
        '''-- ======================================================================
        '''-- Author:		Muhammad Zakee
        '''-- Create date: 05-Jan-11
        '''-- Description:	
        '''-- ======================================================================
        '''-- ------------ Modification History ------------------------------------
        '''-- Author	Date		Details
        '''-- ------   ----        -------
        '''-- - [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property upgrade_02_03_02_38_to_02_03_02_39() As String
            Get
                Return ResourceManager.GetString("upgrade_02_03_02_38_to_02_03_02_39", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF NOT EXISTS (SELECT o.[NAME] FROM sysobjects o WHERE o.[Name] =&apos;Sec_FormControlPermission&apos;)
        '''	CREATE TABLE dbo.Sec_FormControlPermission(
        '''		Co_ID SMALLINT NOT NULL,
        '''		RoleID INT NOT NULL,
        '''		FormID SMALLINT NOT NULL,
        '''		ControlID SMALLINT NOT NULL,
        '''		IsVisible BIT NOT NULL,
        '''		IsEnabled BIT NOT NULL,
        '''		[Stamp_UserID] INT NOT NULL,
        '''		[Stamp_DateTime] DATETIME NOT NULL,
        '''		[Uploaded] BIT NULL,
        '''		[RecordStatus_ID] INT NOT NULL,
        '''	 CONSTRAINT [PK_SecFormControlPermission] PRIMARY KEY CLUSTERED
        '''	(
        '''		Co [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property upgrade_02_03_02_39_to_02_03_03_40() As String
            Get
                Return ResourceManager.GetString("upgrade_02_03_02_39_to_02_03_03_40", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF EXISTS (SELECT * FROM sysObjects o WHERE o.[name] = &apos;spGetInsertAndUpdateCommandQuery&apos;)
        '''	DROP PROC spGetInsertAndUpdateCommandQuery
        '''go
        '''CREATE PROCEDURE dbo.spGetInsertAndUpdateCommandQuery
        '''	(
        '''	@TableName VARCHAR(200)
        '''	)
        '''AS
        '''BEGIN
        '''	DECLARE @PkColumns VARCHAR(1000)
        '''	DECLARE @Columns VARCHAR(2000)
        '''	DECLARE @ValueColumns VARCHAR(MAX)
        '''	DECLARE @UpdateSetPart VARCHAR(MAX)
        '''	DECLARE @Query AS VARCHAR(8000)
        '''
        '''	SET NOCOUNT ON
        '''
        '''	SET @PkColumns = &apos;&apos;
        '''	SET @Columns = &apos;&apos;
        '''	SET @ValueColumns = &apos;&apos;
        '''	SET @ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property upgrade_02_03_03_41_to_02_03_03_42() As String
            Get
                Return ResourceManager.GetString("upgrade_02_03_03_41_to_02_03_03_42", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF NOT EXISTS (SELECT C.[NAME] FROM sysobjects o INNER JOIN syscolumns c ON o.id=c.id WHERE o.[Name] =&apos;Accounting_Voucher_Detail&apos; AND c.[Name]=&apos;Upload_DateTime&apos;) 
        '''ALTER TABLE Accounting_Voucher_Detail ADD Upload_DateTime datetime NULL
        '''go
        '''IF NOT EXISTS (SELECT C.[NAME] FROM sysobjects o INNER JOIN syscolumns c ON o.id=c.id WHERE o.[Name] =&apos;Person&apos; AND c.[Name]=&apos;Upload_DateTime&apos;) 
        '''ALTER TABLE Person ADD Upload_DateTime datetime NULL
        '''go
        '''IF NOT EXISTS (SELECT C.[NAME] FROM sysobjects o INNER JOIN syscolum [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Upgrade1370To1380() As String
            Get
                Return ResourceManager.GetString("Upgrade1370To1380", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF EXISTS (SELECT o.[NAME] FROM sysobjects o WHERE o.[Name] =&apos;trigUpdateStock&apos;)
        '''DROP TRIGGER trigUpdateStock
        '''GO
        '''-- =============================================
        '''-- Author:		Faisal
        '''-- Create date: 23-Nov-2008
        '''-- Description:	
        '''-- =============================================
        '''CREATE TRIGGER [dbo].[trigUpdateStock] 
        '''   ON  [dbo].[Inventory_Detail] 
        '''   AFTER INSERT,DELETE,UPDATE
        '''AS 
        '''DECLARE @Factor AS INT
        '''
        '''	IF (SELECT Count(*) FROM Deleted) &gt;0
        '''		BEGIN
        '''		IF (SELECT Count(*) FROM Inv_Stock WHERE Co [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Upgrade1380To1390() As String
            Get
                Return ResourceManager.GetString("Upgrade1380To1390", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF EXISTS (SELECT o.[NAME] FROM sysobjects o WHERE o.[Name] =&apos;spGetInventoryDetails&apos;)
        '''	DROP PROCEDURE spGetInventoryDetails
        '''go
        '''CREATE PROCEDURE [dbo].[spGetInventoryDetails] 
        '''AS 
        '''BEGIN 
        '''	SELECT inv.Co_ID, Co.Co_Desc, 
        '''		invdet.Item_ID, inv.Party_ID, 
        '''		item.Item_Code, item.Item_Desc, 
        '''		cat.Item_Desc AS Item_Category, inv.Inventory_Date, 
        '''		inv.Payment_Mode, inv.Remarks,	
        '''		inv.Inventory_ID, inv.Inventory_No, 
        '''		invdet.DocumentType_ID, doc.DocumentType_Desc, 
        '''		invdet.Inventory_Qty_Size01, invd [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Upgrade1390To1391() As String
            Get
                Return ResourceManager.GetString("Upgrade1390To1391", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF NOT EXISTS (SELECT [Setting_Id] FROM [Base_Setting] WHERE [Setting_Id] =&apos;ItemDescLevel&apos;) 
        '''	INSERT INTO [Base_Setting]
        '''       ([Co_Id],[User_Id],[Setting_Id]
        '''       ,[Setting_Desc]
        '''       ,[Setting_Value],[Stamp_User_Id],[Stamp_DateTime],[Setting_Value_DataType]
        '''       ,[Setting_Value_MinimumValue],[Setting_Value_MaximumValue],[Upload_DateTime])
        '''  VALUES
        '''       (0,0,&apos;ItemDescLevel&apos;
        '''       ,&apos;When user will enter item code then description of this specified level will be shown intead of entered code [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Upgrade1391To1392() As String
            Get
                Return ResourceManager.GetString("Upgrade1391To1392", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF NOT EXISTS (SELECT [Setting_Id] FROM [Base_Setting] WHERE [Setting_Id] =&apos;DBColumnCaptionItem_MinStock_Size0&apos;) 
        '''	INSERT INTO [Base_Setting]
        '''       ([Co_Id],[User_Id],[Setting_Id]
        '''       ,[Setting_Desc]
        '''       ,[Setting_Value],[Stamp_User_Id],[Stamp_DateTime],[Setting_Value_DataType]
        '''       ,[Setting_Value_MinimumValue],[Setting_Value_MaximumValue],[Upload_DateTime])
        '''  VALUES
        '''       (0,0,&apos;DBColumnCaptionItem_MinStock_Size0&apos;
        '''       ,&apos;Item_MinStock_Size0 Caption&apos;
        '''       ,&apos;100&apos;,0,GetDate(),&apos;String&apos;
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Upgrade1392To1400() As String
            Get
                Return ResourceManager.GetString("Upgrade1392To1400", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF NOT EXISTS (SELECT C.[NAME] FROM sysobjects o INNER JOIN syscolumns c ON o.id=c.id WHERE o.[Name] =&apos;Inv_Item&apos; AND c.[Name]=&apos;Item_MinStock_Size0&apos;)
        '''	ALTER TABLE Inv_Item ADD Item_MinStock_Size0 int NULL
        '''go
        '''IF NOT EXISTS (SELECT C.[NAME] FROM sysobjects o INNER JOIN syscolumns c ON o.id=c.id WHERE o.[Name] =&apos;Inv_Item&apos; AND c.[Name]=&apos;Item_MinStock_Size1&apos;)
        '''	ALTER TABLE Inv_Item ADD Item_MinStock_Size1 int NULL
        '''go
        '''IF NOT EXISTS (SELECT C.[NAME] FROM sysobjects o INNER JOIN syscolumns c ON o.id=c.id WHERE  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property upgrade1400To1410() As String
            Get
                Return ResourceManager.GetString("upgrade1400To1410", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF EXISTS (SELECT o.[NAME] FROM sysobjects o WHERE o.[Name] =&apos;Inv_Stock&apos;)
        '''	exec sp_rename &apos;Inv_Stock&apos;, &apos;Inv_ItemSummary&apos;
        '''go
        '''IF EXISTS (SELECT C.[NAME] FROM sysobjects o INNER JOIN syscolumns c ON o.id=c.id WHERE o.[Name] =&apos;Inv_ItemSummary&apos; AND c.[Name]=&apos;Item_Stock_Size01&apos;)
        '''	exec sp_rename &apos;Inv_ItemSummary.Item_Stock_Size01&apos;, &apos;ItemSummary_Size01&apos;
        '''go
        '''IF EXISTS (SELECT C.[NAME] FROM sysobjects o INNER JOIN syscolumns c ON o.id=c.id WHERE o.[Name] =&apos;Inv_ItemSummary&apos; AND c.[Name]=&apos;Item_Stock_Size02&apos;)
        '''	exe [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property upgrade1410to2000() As String
            Get
                Return ResourceManager.GetString("upgrade1410to2000", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF NOT EXISTS (SELECT C.[NAME] FROM sysobjects o INNER JOIN syscolumns c ON o.id=c.id WHERE o.[Name] =&apos;Base_Setting&apos; AND c.[Name]=&apos;Upload_DateTime&apos;) 
        '''	ALTER TABLE Base_Setting ADD Upload_DateTime DATETIME NULL
        '''go
        '''IF NOT EXISTS (SELECT [Setting_Id] FROM [Base_Setting] WHERE [Setting_Id] =&apos;DBColumnCaptionItemSummary_Size01&apos;) 
        '''	INSERT INTO [Base_Setting]
        '''       ([Co_Id],[User_Id],[Setting_Id]
        '''       ,[Setting_Desc]
        '''       ,[Setting_Value],[Stamp_User_Id],[Stamp_DateTime],[Setting_Value_DataType]
        '''       [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property upgrade2000to20001() As String
            Get
                Return ResourceManager.GetString("upgrade2000to20001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to -- =============================================
        '''-- Author:		Faisal Saleem
        '''-- Create date: 01-Mar-2009
        '''-- Description:	This stored procedure returns the records from inventory and
        '''--				inventorydetail table to be used in report. It does not perform
        '''--				any calculations.
        '''-- =============================================
        '''-- ------------ Modification History -----------
        '''-- Author	Date		Details
        '''-- ------   ----        -------
        '''-- Faisal	01-Mar-2009	Added Comment header and because primary key is chan [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property upgrade20011to20012() As String
            Get
                Return ResourceManager.GetString("upgrade20011to20012", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF NOT EXISTS (SELECT o.[NAME] FROM sysobjects o WHERE o.[Name] =&apos;Inv_ItemSummary&apos;)
        '''	CREATE TABLE [Inv_ItemSummary](
        '''		[Co_ID] [smallint] NOT NULL,
        '''		[Source_First_ID] [int] NOT NULL,
        '''		[Source_Second_ID] [int] NOT NULL,
        '''		[Source_DocumentType_ID] [int] NOT NULL,
        '''		[Warehouse_ID] [int] NOT NULL,
        '''		[ItemSummary_Size01] [decimal](18, 0) NOT NULL,
        '''		[ItemSummary_Size02] [decimal](18, 0) NOT NULL,
        '''		[ItemSummary_Size03] [decimal](18, 0) NOT NULL,
        '''		[ItemSummary_Size04] [decimal](18, 0) NOT NULL,
        '''		[I [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property upgrade2003to2004() As String
            Get
                Return ResourceManager.GetString("upgrade2003to2004", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF EXISTS (SELECT O.[NAME] FROM sysobjects o WHERE o.[Name] =&apos;PK_Inventory&apos;)
        '''	ALTER TABLE Inventory 
        '''		DROP CONSTRAINT PK_Inventory
        '''GO
        '''IF NOT EXISTS (SELECT O.[NAME] FROM sysobjects o WHERE o.[Name] =&apos;PK_Inventory&apos;)
        '''	ALTER TABLE Inventory 
        '''		ADD CONSTRAINT PK_Inventory PRIMARY KEY CLUSTERED
        '''		(Co_ID, Inventory_ID, DocumentType_ID)
        '''GO
        '''IF EXISTS (SELECT O.[NAME] FROM sysobjects o WHERE o.[Name] =&apos;PK_Inventory_Detail&apos;)
        '''	ALTER TABLE Inventory_Detail 
        '''		DROP CONSTRAINT PK_Inventory_Detail
        '''GO
        '''IF NOT  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property upgrade2006to2007() As String
            Get
                Return ResourceManager.GetString("upgrade2006to2007", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF EXISTS (SELECT O.[NAME] FROM sysobjects o WHERE o.[Name] =&apos;spDailyStock&apos;)
        '''	DROP PROCEDURE spDailyStock
        '''GO
        '''-- =============================================
        '''-- Author:		Noman Latif
        '''-- Create date: 28 Sep 2008
        '''-- Description:	This stored procedure is used for
        '''--              to calculate the stock.
        '''-- =============================================
        '''CREATE PROCEDURE spDailyStock
        '''	-- Add the parameters for the stored procedure here
        '''	--@From_Date Datetime = &apos;1900/01/01&apos;, 
        '''	--@To_Date Datetime = &apos;2008 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Upgrade2007to2008() As String
            Get
                Return ResourceManager.GetString("Upgrade2007to2008", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF NOT EXISTS (SELECT Menu_Id FROM Base_Menu WHERE Menu_Id =307) 
        '''	INSERT INTO [Base_Menu] ([Menu_Id], [Menu_Desc], [Form_Id], 
        '''		[Display_Order], [Parent_Menu_Id], [Stamp_UserId], [Stamp_DateTime], [Upload_DateTime]) 
        '''	VALUES (307, &apos;Erp &amp;Configuration&apos;, &apos;03-007&apos;, 7, 300, 0, GetDate(), NULL)
        '''GO
        '''IF NOT EXISTS (SELECT [Setting_Id] FROM [Base_Setting] WHERE [Setting_Id] =&apos;ReportFooterText.PosSalesInvoiceReport&apos;) 
        '''	INSERT INTO [Base_Setting]
        '''       ([Co_Id],[User_Id],[Setting_Id]
        '''       ,[Setting_Desc]        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Upgrade2008to2009() As String
            Get
                Return ResourceManager.GetString("Upgrade2008to2009", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Warning() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Warning", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
